### ISSUE TITLE
Linux-aarch64 is unsupported for release 2.20.2

### ISSUE THREAD

**Issue by nikaro** [getsentry/sentry-cli#1704]
### Environment

What version of the CLI and what OS are you running?

A Debian container running on an Apple M1.

### Steps to Reproduce

What you did?

* Start a shell in a container
* Try to install sentry-cli 2.20.2

```
> docker run -it --rm debian:latest bash
root@2bca6c405499:/# rm -rf /usr/local/bin/sentry-cli
root@2bca6c405499:/# export SENTRY_CLI_VERSION=2.20.1
root@2bca6c405499:/# curl -sL https://sentry.io/get-cli/ | bash
This script will automatically install sentry-cli (2.20.1) for you.
Installation path: /usr/local/bin/sentry-cli
Warning: this script is currently running as root. This is dangerous.
         Instead run it as normal user. We will sudo as needed.
######################################################################## 100.0%#=#=#                             ######################################################################## 100.0%
Installed sentry-cli 2.20.1
Done!
root@2bca6c405499:/# rm -rf /usr/local/bin/sentry-cli
root@2bca6c405499:/# export SENTRY_CLI_VERSION=2.20.2
root@2bca6c405499:/# curl -sL https://sentry.io/get-cli/ | bash
This script will automatically install sentry-cli (2.20.2) for you.
Installation path: /usr/local/bin/sentry-cli
Warning: this script is currently running as root. This is dangerous.
         Instead run it as normal user. We will sudo as needed.
######################################################################## 100.0%
error: your platform and architecture (Linux-aarch64) is unsupported.
```

### Expected/Actual Result

Install sentry-cli 2.20.2.

### Logs

Ø

**Comment by kamilogorek** [comment]
We had a small release hiccup, the latest release should be fixed.

**Comment by nikaro** [comment]
Actually this is still not fixed, but it looks like more an issue with `release-registry.services.sentry.io` than with the release itself.

```
> curl -I "https://release-registry.services.sentry.io/apps/sentry-cli/2.20.3?response=download&arch=x86_64&platform=Linux&package=sentry-cli"
HTTP/2 404
content-type: text/html
content-length: 232
access-control-allow-origin: *
x-envoy-upstream-service-time: 1
date: Tue, 01 Aug 2023 11:18:03 GMT
server: envoy
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

> curl -I "https://release-registry.services.sentry.io/apps/sentry-cli/2.20.1?response=download&arch=x86_64&platform=Linux&package=sentry-cli"
HTTP/2 302
content-type: text/html; charset=utf-8
content-length: 355
location: https://downloads.sentry-cdn.com/sentry-cli/2.20.1/sentry-cli-Linux-x86_64
digest: sha256=NgOVbs3+A/qJFIcf04leGM7iJh/e9PUHCrBS0MoJTDw=
access-control-allow-origin: *
x-envoy-upstream-service-time: 2
date: Tue, 01 Aug 2023 11:18:12 GMT
server: envoy
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

> curl -I "https://release-registry.services.sentry.io/apps/sentry-cli/2.20.1?response=download&arch=aarch64&platform=Linux&package=sentry-cli"
HTTP/2 302
content-type: text/html; charset=utf-8
content-length: 357
location: https://downloads.sentry-cdn.com/sentry-cli/2.20.1/sentry-cli-Linux-aarch64
digest: sha256=W2Sm3yGcBlzbXAUC8DViRhttAdPcq8j0mU9oqrBXEKQ=
access-control-allow-origin: *
x-envoy-upstream-service-time: 1
date: Tue, 01 Aug 2023 11:18:35 GMT
server: envoy
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

> curl -I "https://release-registry.services.sentry.io/apps/sentry-cli/2.20.3?response=download&arch=aarch64&platform=Linux&package=sentry-cli"
HTTP/2 404
content-type: text/html
content-length: 232
access-control-allow-origin: *
x-envoy-upstream-service-time: 1
date: Tue, 01 Aug 2023 11:18:47 GMT
server: envoy
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

**Comment by kamilogorek** [comment]
Good catch, thanks! Registry has been fixed and all previous releases will work as well.
